name: CI/CD with Docker Compose

on:
  push:
    paths:
      - "week5/**"


jobs:
  build:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: week5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./week5
          file: ./week5/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/week5-web:latest


  integration-test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: week5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up Docker
        uses: docker/setup-docker-action@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Run integration tests with docker-compose
        run: docker compose -f docker-compose.test.yml up --abort-on-container-exit --build
